# Generated by Django 2.1.2 on 2019-11-29 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caigouyuan',
            fields=[
                ('caigouyuan_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('caigouyuan_name', models.CharField(max_length=100)),
                ('caigouyuan_sex', models.CharField(max_length=4)),
                ('caigouyuan_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='cangku',
            fields=[
                ('cangku_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('weizhi_cangku', models.CharField(max_length=100)),
                ('cangku_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='dingdan',
            fields=[
                ('dingdan_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('digndan_time', models.DateTimeField()),
                ('shangpin_set_dingdan', models.TextField()),
                ('zongjia_dingdan', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='electrical',
            fields=[
                ('elec_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('I_A_in', models.FloatField()),
                ('I_B_in', models.FloatField()),
                ('I_C_in', models.FloatField()),
                ('I_A_out', models.FloatField()),
                ('I_B_out', models.FloatField()),
                ('I_C_out', models.FloatField()),
                ('U_A', models.FloatField()),
                ('U_B', models.FloatField()),
                ('U_C', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='huojia',
            fields=[
                ('huojia_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('xiangduiweizhi_huojia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='huowu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changjia_huowu', models.CharField(max_length=50)),
                ('huowuming_huowu', models.CharField(max_length=100)),
                ('jinjia_huowu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='huowu_id_set',
            fields=[
                ('huowu_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('huowu_ming_id_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.huowu')),
            ],
        ),
        migrations.CreateModel(
            name='jingli',
            fields=[
                ('jingli_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('jingli_name', models.CharField(max_length=100)),
                ('jingli_sex', models.CharField(max_length=4)),
                ('jingli_birth', models.DateField()),
                ('jingli_salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='jinhuodan',
            fields=[
                ('jinghuodan_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('huowu_set', models.TextField()),
                ('shijian_jinhuodan', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls_id', models.CharField(default='lei_13130', max_length=20)),
                ('shangpin_id', models.CharField(max_length=20)),
                ('length', models.CharField(max_length=8, null=True)),
                ('for_sex', models.CharField(max_length=4, null=True)),
                ('color', models.CharField(max_length=10, null=True)),
                ('materials', models.CharField(max_length=50, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='liansuodian',
            fields=[
                ('liansuodian_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('weizhi_liansuodian', models.CharField(max_length=100)),
                ('liansuodian_phone', models.CharField(max_length=15)),
                ('jingli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.jingli')),
            ],
        ),
        migrations.CreateModel(
            name='qingdan',
            fields=[
                ('qingdan_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('zongjia_qingdan', models.FloatField()),
                ('shangpin_set_qingdan', models.TextField()),
                ('shijian_qingdan', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('gongzitiaomu_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('jichugongzi', models.FloatField()),
                ('jixiao', models.FloatField()),
                ('chuqin', models.FloatField()),
                ('weigui', models.FloatField()),
                ('shuijin', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='shangpin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changjia_shangpin', models.CharField(max_length=50)),
                ('shangpinming_shangpin', models.CharField(max_length=100)),
                ('danjia', models.FloatField()),
                ('baozhiqi', models.FloatField()),
                ('huojia_id', models.ManyToManyField(to='supermarket.huojia')),
            ],
        ),
        migrations.CreateModel(
            name='shangpin_id_set',
            fields=[
                ('shangpin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('shengchanriqi', models.DateField()),
                ('fenlei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.Lei')),
                ('shangpinming_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.shangpin')),
            ],
        ),
        migrations.CreateModel(
            name='shangpin_online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changjia_shangpin_online', models.CharField(max_length=50)),
                ('shangpinming_shangpin_online', models.CharField(max_length=100)),
                ('danjia', models.FloatField()),
                ('baozhiqi', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='shouyinyuan',
            fields=[
                ('shouyinyuan_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('shouyinyuan_name', models.CharField(max_length=100)),
                ('shouyinyuan_sex', models.CharField(max_length=4)),
                ('shouyinyuan_birth', models.DateField()),
                ('shouyinyuan_salary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supermarket.salary')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('shenfenzheng', models.CharField(max_length=20)),
                ('user_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vip',
            fields=[
                ('vip_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vip_level', models.IntegerField()),
                ('yonghu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supermarket.user')),
            ],
        ),
        migrations.CreateModel(
            name='zhangdan',
            fields=[
                ('zhangdan_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('shijian_zhangdan', models.DateField()),
                ('xiaoshoue', models.FloatField(null=True)),
                ('liansuodian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.liansuodian')),
            ],
        ),
        migrations.CreateModel(
            name='zhekou',
            fields=[
                ('zhekoutiaomu_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('discount', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shangpin_online',
            name='zhekou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.zhekou'),
        ),
        migrations.AddField(
            model_name='shangpin',
            name='zhekou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.zhekou'),
        ),
        migrations.AddField(
            model_name='qingdan',
            name='shouyinyuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.shouyinyuan'),
        ),
        migrations.AddField(
            model_name='qingdan',
            name='zhangdan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.zhangdan'),
        ),
        migrations.AlterUniqueTogether(
            name='lei',
            unique_together={('cls_id', 'shangpin_id')},
        ),
        migrations.AddField(
            model_name='jingli',
            name='gongzi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supermarket.salary'),
        ),
        migrations.AddField(
            model_name='huowu',
            name='jinghuodan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rely_to_jinhuodan', to='supermarket.jinhuodan'),
        ),
        migrations.AddField(
            model_name='huojia',
            name='liansuodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.liansuodian'),
        ),
        migrations.AddField(
            model_name='dingdan',
            name='yonghu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.user'),
        ),
        migrations.AddField(
            model_name='dingdan',
            name='zhangdan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.zhangdan'),
        ),
        migrations.AddField(
            model_name='caigouyuan',
            name='caigouyuan_salary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supermarket.salary'),
        ),
        migrations.AlterUniqueTogether(
            name='shangpin_online',
            unique_together={('changjia_shangpin_online', 'shangpinming_shangpin_online')},
        ),
        migrations.AlterUniqueTogether(
            name='shangpin',
            unique_together={('changjia_shangpin', 'shangpinming_shangpin')},
        ),
        migrations.AlterUniqueTogether(
            name='huowu',
            unique_together={('changjia_huowu', 'huowuming_huowu')},
        ),
    ]
