# Generated by Django 2.1.2 on 2019-11-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shangpin_id_set',
            name='fenlei',
        ),
    ]
