# Generated by Django 2.1.2 on 2019-12-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0003_shangpin_id_set_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dingdan',
            name='shangpin_set_dingdan',
            field=models.TextField(max_length=200),
        ),
    ]
