# Generated by Django 2.1.2 on 2019-12-03 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0005_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dingdan',
            name='yonghu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarket.user'),
        ),
    ]
