# Generated by Django 2.1.2 on 2019-12-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0006_auto_20191203_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xiaofei',
            field=models.FloatField(null=True),
        ),
    ]
