# Generated by Django 2.1.2 on 2019-12-06 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0007_user_xiaofei'),
    ]

    operations = [
        migrations.AddField(
            model_name='jingli',
            name='employee_status',
            field=models.OneToOneField(default='jingli_hwq', on_delete=django.db.models.deletion.CASCADE, to='supermarket.Employee'),
            preserve_default=False,
        ),
    ]
