# Generated by Django 2.1.2 on 2019-12-06 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0009_shouyinyuan_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='caigouyuan',
            name='employee_status',
            field=models.OneToOneField(default='caigou_hwq', on_delete=django.db.models.deletion.CASCADE, to='supermarket.Employee'),
            preserve_default=False,
        ),
    ]
