# Generated by Django 2.1.2 on 2019-12-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0013_salary_shijian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhangdan',
            name='liansuodian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zhangdans', to='supermarket.liansuodian'),
        ),
        migrations.AlterUniqueTogether(
            name='zhangdan',
            unique_together={('zhangdan_id', 'liansuodian')},
        ),
    ]
