# Generated by Django 2.1.2 on 2019-12-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0015_auto_20191206_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='salary_summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gongzitiaomu_id', models.CharField(max_length=20)),
                ('shijian', models.DateField(null=True)),
                ('jichugongzi', models.FloatField()),
                ('jixiao', models.FloatField()),
                ('chuqin', models.FloatField()),
                ('weigui', models.FloatField()),
                ('shuijin', models.FloatField()),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gongzis', to='supermarket.Employee')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='salary_summary',
            unique_together={('gongzitiaomu_id', 'shijian')},
        ),
    ]
