# Generated by Django 2.1.2 on 2019-12-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0016_auto_20191207_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caigouyuan',
            name='caigouyuan_salary',
        ),
        migrations.RemoveField(
            model_name='jingli',
            name='gongzi',
        ),
        migrations.RemoveField(
            model_name='shouyinyuan',
            name='shouyinyuan_salary',
        ),
    ]
