# Generated by Django 2.1.2 on 2019-12-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0019_auto_20191208_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='xiaofei',
            field=models.FloatField(default=0, null=True),
        ),
    ]
