# Generated by Django 2.1.2 on 2019-12-08 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0021_auto_20191208_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='yonghu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_vip', to='supermarket.user'),
        ),
    ]
